services:
  - type: web
    name: yt-downloader
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      bash fetch_cookies.sh && gunicorn yt_downloader.wsgi:application
