services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p downloads
    startCommand: gunicorn downloader.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: YTDLP_NO_UPDATE
        value: "1"
