services:
  - type: web
    name: yt-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python fetch_cookies.py && gunicorn yt_downloader.wsgi:application
